// <auto-generated />
namespace Gallery.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImageAndTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageAndTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201509292117112_ImageAndTag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
